AWSTemplateFormatVersion: "2010-09-09"
Description: "Media Insights Engine - Workflow to run all MIE analyses"

Parameters:
  WorkflowCustomResourceArn:
    Type: String
    Description: "ARN of the Media Insights custom resource that handles creating operations, stages and workflows"
  StepfunctionRoleArn:
    Type: String
  GenericDataLookup:
    Type: String
  CelebRecognition:
    Type: String
  ContentModeration:
    Type: String
  FaceDetection:
    Type: String
  FaceSearch:
    Type: String
  LabelDetection:
    Type: String
  PersonTracking:
    Type: String
  Mediaconvert:
    Type: String
  Mediainfo:
    Type: String
  Thumbnail:
    Type: String
  Transcribe:
    Type: String
  Translate:
    Type: String
  ComprehendPhrases:
    Type: String
  ComprehendEntities:
    Type: String
  Polly:
    Type: String

Resources:
  defaultPrelimVideoStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "defaultPrelimVideoStage"
      Operations:
        - !Ref Thumbnail
        - !Ref Mediainfo
  defaultVideoStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "defaultVideoStage"
      Operations:
        - !Ref GenericDataLookup
        - !Ref CelebRecognition
        - !Ref ContentModeration
        - !Ref FaceDetection
        - !Ref FaceSearch
        - !Ref LabelDetection
        - !Ref PersonTracking
        - !Ref Mediaconvert

  defaultAudioStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "defaultAudioStage"
      Operations:
        - !Ref Transcribe

  defaultTextStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "defaultTextStage"
      Operations:
        - !Ref Translate
        - !Ref ComprehendPhrases
        - !Ref ComprehendEntities

  defaultTextSynthesisStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "defaultTextSynthesisStage"
      Operations:
        - !Ref Polly

  MieCompleteWorkflow:
    DependsOn:
      - defaultPrelimVideoStage
      - defaultVideoStage
      - defaultAudioStage
      - defaultTextStage
      - defaultTextSynthesisStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: "MieCompleteWorkflow"
      RoleArn: !Ref StepfunctionRoleArn
      StartAt: !GetAtt defaultPrelimVideoStage.Name
      Stages: !Sub
        - |-
          {
            "${defaultPrelimVideoStage}":{
              "Next": "${defaultVideoStage}"
              },
            "${defaultVideoStage}":{
              "Next": "${defaultAudioStage}"
              },
            "${defaultAudioStage}":{
              "Next": "${defaultTextStage}"
              },
            "${defaultTextStage}":{
              "Next": "${defaultTextSynthesisStage}"
              },
            "${defaultTextSynthesisStage}":{
              "End": true
              }
          }
        - {
          defaultPrelimVideoStage: !GetAtt defaultPrelimVideoStage.Name,
          defaultVideoStage: !GetAtt defaultVideoStage.Name,
          defaultAudioStage: !GetAtt defaultAudioStage.Name,
          defaultTextStage: !GetAtt defaultTextStage.Name,
          defaultTextSynthesisStage: !GetAtt defaultTextSynthesisStage.Name
        }

